[General]
logLevel = 2 #0 trace; 1 debug; 2 info
avatarSet = 0 #0 orginal, 1 variant 
hideFaction = false #some information could be a spoiler

[Mods]
handToHand = false #Hand to Hand - An Adamant Addon, lockpicking -> Hand to Hand, pickpocket -> Security